[project]
name = "RLT-pytorch"
version = "0.1.6"
description = "Recurrent Looped Transformer - Pytorch"
authors = [
    { name = "Phil Wang", email = "lucidrains@gmail.com" }
]
readme = "README.md"
requires-python = ">= 3.10"
license = { file = "LICENSE" }
keywords = [
    'artificial intelligence',
    'deep learning',
    'recurrent looped transformer',
    'latent reasoning',
]

classifiers=[
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Topic :: Scientific/Engineering :: Artificial Intelligence',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.10',
]

dependencies = [
    "einx>=0.4.0",
    "einops>=0.8.0",
    "rotary-embedding-torch>=0.6.0",
    "torch>=2.5",
    "torch-einops-utils>=0.1.28",
    "x-mlps-pytorch>=0.5.1",
]

[project.urls]
Homepage = "https://pypi.org/project/RLT-pytorch/"
Repository = "https://github.com/lucidrains/RLT"

[project.optional-dependencies]
examples = []
test = [
    "pytest",
    "stack-attention-pytorch>=0.0.8"
]

[tool.pytest.ini_options]
pythonpath = [
    "."
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build]
include = [
    "RLT",
    "pyproject.toml",
    "README.md",
    "LICENSE"
]

[tool.hatch.build.targets.wheel]
packages = ["RLT"]
